#158792715 Set up a signup endpoint
elikeyz/ride-my-way pull request #11
Opened 2018-07-03 16:16 UTC by elikeyz

### What does this PR do?
Set up an endpoint for creating a new user account
#### Description of Task to be completed?
- Write a POST request for creating a new user account and generating a JSON Web Token
- Write tests for the endpoint
#### How should this be manually tested?
Test endpoint with Postman and run tests in the command line with "npm test"
#### What are the relevant pivotal tracker stories?
#158792715
#158800700

2018-07-03 21:24 UTC, fob413 commented
I can see that your test coverage dropped a lot. Any plans on handling that?

2018-07-03 21:26 UTC, fob413 requested changes

2018-07-03 21:26 UTC, fob413 commented on controllers/users.js
> +const connectString = 'postgres://postgres:mastahacka@localhost:5432/rides';
Look into having this connection to the database done in a file somewhere and exported out. That way all you have to do in all your controller files is just to import the connected database.

2018-07-04 07:39 UTC, elikeyz commented on controllers/users.js
> +const connectString = 'postgres://postgres:mastahacka@localhost:5432/rides';
Ok

2018-07-04 09:14 UTC, fob413 requested changes

2018-07-04 09:14 UTC, fob413 commented on utils/validate.js
> +    res.status(400).send('Please enter your password');
you've not tested this yet

2018-07-04 09:26 UTC, merged